### ISSUE TITLE
Add support for the new HANA certified VMs SKUs

### ISSUE THREAD

**Issue by KimForss** [Azure/sap-hana#615]
There are new Hana supported SKUs (Azure Esv3 family and the Edsv4) however they require Ultra disk for the log volumes.

Out current disk size schema does not support providing the IOPS for Ultradisk
https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html#disk_iops_read_write

{
                "name": "log",
                "count": 3,
                "disk_type": "Premium_LRS",
                "size_gb": 255,
                "caching": "None",
                "write_accelerator": true,
                "mount_point": "/hana/log"
  }

can we add an IOPS property to the schema?

**Comment by rukawata** [comment]
@KimForss, this should be possible. Two qeustions:
- Do we know if all data disks used by HANA are ultra SSD? If not, how do we identify that? The reason I'm asking that is because `disk_iops_read_write` is only settable for ultra SSD.
- If we set a value for `IOPS` in `hdb_sizes.json`, will this reflect `IOPS` column in the disk configuration table in [this reference doc](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage)?

Thanks,
Nancy

**Comment by KimForss** [comment]
Ultra would primarily be for log disks because of cost reasons, I don't think we need to identify it as I believe Terraform will only use that property if the SKU is UltraSSD_LRS (https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html) - but not 100% sure

Yes if we set the IOPS we would set the value to match the documentation

**Comment by KimForss** [comment]
Closed with https://github.com/Azure/sap-hana/releases/tag/v2.3.0-beta
